### ISSUE TITLE
Invalid Token Check in calculateReturnToMerchantSignature()

### ISSUE THREAD

**Issue by ahmed-syam** [payfort/php-payfort#4]
method : calculateReturnToMerchantSignature()
will always get invalid token, because it hashes status and response message ...etc 

only unset signature from url paramaters and other paramters hashed so always sent and calculated after return will be mismatched

**Comment by mohannadsaleh** [comment]
Thanks for your valuable comment , we have fixed this issue and the fix is launched on github .
enjoy using the library and nice to e-meet you ahmed .

Please feel free to contact us anytime if you have any further questions or any extra help needed .

Best Regards,
Mohannad Saleh
