### ISSUE TITLE
getting Error 13666 when sending request to Payfort sandbox environment

### ISSUE THREAD

**Issue by zeeshanbeyg** [payfort/php-payfort#7]
Sometime my request to payfort test environment is successful but when i try again its sending me transaction declined error message

This is my success request in request response log (Success Case)

{"amount":"11700","merchant_reference":"cb7adc9d-c612-445c-8","access_code":"UVxNEBltRnFGjwMVeaaX","status":"","3ds_url":"","command":"PURCHASE","customer_name":"zeeshanbaigs","customer_email":"aaa@yahoo.com","token_name":"ZQVbeAGO7","language":"en","merchant_identifier":"gzQTdZHQ","signature":"8dbe6abf113bd81f1bb3bf69153246fd62de111513760c7cf5e287406e1ba934","currency":"SAR"}

but when i sent again a different request (Failure Case)

{"amount":"28350","merchant_reference":"5e2bf9c5-6b05-4b2a-a","access_code":"UVxNEBltRnFGjwMVeaaX","status":"","3ds_url":"","command":"PURCHASE","customer_name":"zeeshanbaigs","customer_email":"aaa@yahoo.com","token_name":"MN936bYVA","language":"en","merchant_identifier":"gzQTdZHQ","signature":"c387e39b34e78c496516cfe2b782cb249e17a0bcdd6c34b33b952ec8478662b0","currency":"SAR"}

Please help me if you found anything that i am doing wrong.

**Comment by mohannadsaleh** [comment]
Hello, 

Can you please contact our integration team integration@payfort.com , and provide them with the request/response parameters they will be glad to assist you to solve the mentioned issue .

Best Regards,
